// resources/js/pages/products/Create.vue
<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ArrowLeft, Plus, Trash2 } from '@lucide/vue';
import { computed, watch } from 'vue';
import FormActions from '@/components/forms/FormActions.vue';
import FormField from '@/components/forms/FormField.vue';
import FormSection from '@/components/forms/FormSection.vue';
import ProductImageCropper from '@/components/ProductImageCropper.vue';
import { index as productsIndex, store } from '@/routes/products';

const props = defineProps<{ categories: { id: number; name: string }[] }>();
const inputClass = 'mt-1 block min-h-11 w-full rounded-xl border-slate-200 bg-slate-50 px-3.5 text-sm text-slate-800 outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-100 dark:border-slate-700 dark:bg-slate-800 dark:text-white';
type UnitForm = { name: string; conversion: number; selling_price: number; barcode: string };
const form = useForm({ category_id: props.categories[0]?.id ?? '', name: '', sku: '', product_type: 'standard', base_unit: 'piece', purchase_price: 0, reorder_level: 0, image: null as File | null, units: [{ name: 'piece', conversion: 1, selling_price: 0, barcode: '' }] as UnitForm[] });
const baseUnitOptions = computed(() => {
    const categoryName = props.categories.find((category) => category.id === form.category_id)?.name.toLowerCase() ?? '';

    if (categoryName.includes('alcohol')) {
        return ['Bottle'];
    }

    if (categoryName.includes('beer')) {
        return ['Bottle', 'Can'];
    }

    if (categoryName.includes('soft drink')) {
        return ['Bottle', 'Can'];
    }

    if (categoryName.includes('cigarette') || categoryName.includes('cheroot')) {
        return ['Stick', 'Pack'];
    }

    if (categoryName.includes('snack') || categoryName.includes('other')) {
        return ['Piece', 'Pack'];
    }

    return ['Piece'];
});

watch(baseUnitOptions, (options) => {
    if (!options.includes(form.base_unit)) {
        form.base_unit = options[0];
    }
}, { immediate: true });

function addUnit(): void {
    form.units.push({ name: '', conversion: 1, selling_price: 0, barcode: '' });
}

function removeUnit(index: number): void {
    if (form.units.length > 1) {
        form.units.splice(index, 1);
    }
}

function submit(): void {
    form.post(store().url);
}
</script>

<template>
    <Head title="Add product" />
    <div class="min-h-screen bg-[#f5f7fb] px-4 py-6 text-slate-900 sm:px-6 lg:px-8 dark:bg-slate-950 dark:text-white">
        <div class="mx-auto max-w-4xl space-y-6">
            <Link :href="productsIndex()" class="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-blue-600"><ArrowLeft class="size-4" /> Back to products</Link>
            <header><p class="text-sm font-medium text-blue-600">Catalog setup</p><h1 class="mt-1 text-3xl font-bold tracking-tight">Add product</h1><p class="mt-2 text-sm text-slate-500">Create a product once, then control how it is purchased, stocked, and sold.</p></header>
            <form @submit.prevent="submit" class="space-y-5">
                <FormSection title="Product details" description="The information staff will use to identify this item at checkout.">
                    <div class="grid gap-5 sm:grid-cols-2">
                        <FormField label="Product name" :error="form.errors.name" required><input v-model="form.name" :class="inputClass" required autocomplete="off" /></FormField>
                        <FormField label="SKU" :error="form.errors.sku" hint="Use a unique internal code." required><input v-model="form.sku" :class="inputClass" required autocomplete="off" /></FormField>
                        <FormField label="Category" :error="form.errors.category_id" required><select v-model="form.category_id" :class="inputClass" required><option v-for="category in props.categories" :key="category.id" :value="category.id">{{ category.name }}</option></select></FormField>
                        <FormField label="Base unit" :error="form.errors.base_unit" hint="The smallest stock unit for this category." required><select v-model="form.base_unit" :class="inputClass" required><option v-for="unit in baseUnitOptions" :key="unit" :value="unit">{{ unit }}</option></select></FormField>
                        <FormField label="Purchase price" :error="form.errors.purchase_price" hint="Cost per base unit."><input v-model.number="form.purchase_price" :class="inputClass" type="number" min="0" /></FormField>
                        <FormField label="Reorder level" :error="form.errors.reorder_level" hint="Show a low-stock warning at this quantity."><input v-model.number="form.reorder_level" :class="inputClass" type="number" min="0" /></FormField>
                    </div>
                </FormSection>
                <FormSection title="Product image" description="Add a square image to make this product easier to identify.">
                    <ProductImageCropper v-model="form.image" />
                    <p v-if="form.errors.image" class="mt-3 text-xs font-medium text-rose-600" role="alert">{{ form.errors.image }}</p>
                </FormSection>
                <FormSection title="Selling units" description="Add every unit customers can buy at checkout, such as piece, box, or carton.">
                    <div class="space-y-5">
                        <div v-for="(unit, index) in form.units" :key="index" class="grid gap-5 rounded-xl border border-slate-100 p-4 dark:border-slate-800 sm:grid-cols-3">
                            <FormField label="Unit name" :error="form.errors[`units.${index}.name`]" required><input v-model="unit.name" :class="inputClass" required placeholder="Box" /></FormField>
                            <FormField label="Conversion" :error="form.errors[`units.${index}.conversion`]" hint="Base units in one selling unit." required><input v-model.number="unit.conversion" :class="inputClass" type="number" min="1" required /></FormField>
                            <FormField label="Selling price" :error="form.errors[`units.${index}.selling_price`]" required><div class="flex gap-2"><input v-model.number="unit.selling_price" :class="[inputClass, 'flex-1']" type="number" min="0" required /><button v-if="form.units.length > 1" type="button" @click="removeUnit(index)" class="mt-1 inline-flex min-h-11 items-center justify-center rounded-xl border border-rose-200 px-3 text-rose-600 transition hover:bg-rose-50 dark:border-rose-900 dark:hover:bg-rose-950/40" aria-label="Remove unit"><Trash2 class="size-4" /></button></div></FormField>
                        </div>
                        <button type="button" @click="addUnit" class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-600 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-blue-950/40"><Plus class="size-4" /> Add another unit</button>
                    </div>
                </FormSection>
                <FormActions label="Create product" :processing="form.processing" :cancel-href="productsIndex().url" />
            </form>
        </div>
    </div>
</template>

// resources/js/pages/products/create.tsx
import { Head, Link } from '@inertiajs/react';
import { useForm } from '@inertiajs/react';
import { LoaderCircle, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { products, productsCreate, productsStore, dashboard } from '@/feature-routes';
import type { Category, Unit } from '@/types';

type Props = {
    categories: Category[];
    units: Unit[];
};

export default function ProductsCreate({ categories, units }: Props) {
    const { data, setData, post, processing, errors: formErrors } = useForm({
        category_id: '',
        name: '',
        sku: '',
        image: null,
        brand: '',
        is_active: true,
    });

    const [variants, setVariants] = useState<Array<{
        unit_id: string;
        name: string;
        sku: string;
        units_per_package: string;
        cost_price: string;
        selling_price: string;
        min_stock_level: string;
        max_stock_level: string;
    }>>([]);

    const addVariant = () => {
        setVariants([...variants, {
            unit_id: '',
            name: '',
            sku: '',
            units_per_package: '1',
            cost_price: '0',
            selling_price: '0',
            min_stock_level: '0',
            max_stock_level: '',
        }]);
    };

    const removeVariant = (index: number) => {
        setVariants(variants.filter((_, i) => i !== index));
    };

    const updateVariant = (index: number, field: string, value: string) => {
        const updated = variants.map((v, i) => i === index ? { ...v, [field]: value } : v);
        setVariants(updated);
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        post(productsStore().url, {
            preserveScroll: true,
        });
    };

    return (
        <>
            <Head title="Create Product" />
            <div className="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">
                <div className="flex items-center justify-between">
                    <h1 className="text-2xl font-bold">Create Product</h1>
                    <Link href={products()}>
                        <Button variant="outline">Back to Products</Button>
                    </Link>
                </div>

                <form onSubmit={handleSubmit}>
                    <Card>
                        <CardHeader>
                            <CardTitle>Product Details</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="space-y-2">
                                <Label htmlFor="image">Image</Label>
                                <Input
                                    id="image"
                                    type="file"
                                    accept="image/jpeg,image/png,image/jpg,image/webp"
                                    onChange={(e) => {
                                        const file = e.target.files?.[0];

                                        if (file) {
setData('image', file);
}
                                    }}
                                />
                                {formErrors.image && <p className="text-sm text-destructive">{formErrors.image}</p>}
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label htmlFor="category_id">Category</Label>
                                    <Select value={data.category_id} onValueChange={(v) => setData('category_id', v)}>
                                        <SelectTrigger>
                                            <SelectValue placeholder="Select category" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {categories.map((cat) => (
                                                <SelectItem key={cat.id} value={String(cat.id)}>{cat.name}</SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    {formErrors.category_id && <p className="text-sm text-destructive">{formErrors.category_id}</p>}
                                </div>
                                <div className="space-y-2">
                                    <Label htmlFor="name">Name</Label>
                                    <Input id="name" value={data.name} onChange={(e) => setData('name', e.target.value)} />
                                    {formErrors.name && <p className="text-sm text-destructive">{formErrors.name}</p>}
                                </div>
                                <div className="space-y-2">
                                    <Label htmlFor="sku">SKU</Label>
                                    <Input id="sku" value={data.sku} onChange={(e) => setData('sku', e.target.value)} />
                                    {formErrors.sku && <p className="text-sm text-destructive">{formErrors.sku}</p>}
                                </div>
                                <div className="space-y-2">
                                    <Label htmlFor="brand">Brand</Label>
                                    <Input id="brand" value={data.brand} onChange={(e) => setData('brand', e.target.value)} />
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    <Card className="mt-4">
                        <CardHeader className="flex flex-row items-center justify-between">
                            <CardTitle>Variants</CardTitle>
                            <Button type="button" variant="outline" size="sm" onClick={addVariant}>
                                <Plus className="mr-2 h-4 w-4" /> Add Variant
                            </Button>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            {variants.map((variant, index) => (
                                <div key={index} className="rounded-lg border p-4">
                                    <div className="mb-2 flex items-center justify-between">
                                        <span className="text-sm font-medium">Variant {index + 1}</span>
                                        <Button type="button" variant="ghost" size="icon" onClick={() => removeVariant(index)}>
                                            <Trash2 className="h-4 w-4 text-destructive" />
                                        </Button>
                                    </div>
                                    <div className="grid grid-cols-4 gap-3">
                                        <div className="space-y-1">
                                            <Label className="text-xs">Unit</Label>
                                            <Select value={variant.unit_id} onValueChange={(v) => updateVariant(index, 'unit_id', v)}>
                                                <SelectTrigger>
                                                    <SelectValue placeholder="Unit" />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    {units.map((u) => (
                                                        <SelectItem key={u.id} value={String(u.id)}>{u.name}</SelectItem>
                                                    ))}
                                                </SelectContent>
                                            </Select>
                                        </div>
                                        <div className="space-y-1">
                                            <Label className="text-xs">Name</Label>
                                            <Input value={variant.name} onChange={(e) => updateVariant(index, 'name', e.target.value)} placeholder="e.g. Bottle" />
                                        </div>
                                        <div className="space-y-1">
                                            <Label className="text-xs">SKU</Label>
                                            <Input value={variant.sku} onChange={(e) => updateVariant(index, 'sku', e.target.value)} placeholder="Auto" />
                                        </div>
                                        <div className="space-y-1">
                                            <Label className="text-xs">Units/Pkg</Label>
                                            <Input type="number" step="0.01" value={variant.units_per_package} onChange={(e) => updateVariant(index, 'units_per_package', e.target.value)} />
                                        </div>
                                        <div className="space-y-1">
                                            <Label className="text-xs">Cost Price</Label>
                                            <Input type="number" step="0.01" value={variant.cost_price} onChange={(e) => updateVariant(index, 'cost_price', e.target.value)} />
                                        </div>
                                        <div className="space-y-1">
                                            <Label className="text-xs">Selling Price</Label>
                                            <Input type="number" step="0.01" value={variant.selling_price} onChange={(e) => updateVariant(index, 'selling_price', e.target.value)} />
                                        </div>
                                        <div className="space-y-1">
                                            <Label className="text-xs">Min Stock</Label>
                                            <Input type="number" step="0.01" value={variant.min_stock_level} onChange={(e) => updateVariant(index, 'min_stock_level', e.target.value)} />
                                        </div>
                                        <div className="space-y-1">
                                            <Label className="text-xs">Max Stock</Label>
                                            <Input type="number" step="0.01" value={variant.max_stock_level} onChange={(e) => updateVariant(index, 'max_stock_level', e.target.value)} />
                                        </div>
                                    </div>
                                </div>
                            ))}
                            {variants.length === 0 && (
                                <p className="text-sm text-muted-foreground">Add at least one variant to this product.</p>
                            )}
                        </CardContent>
                    </Card>

                    <div className="mt-4 flex justify-end gap-2">
                        <Link href={products()}>
                            <Button type="button" variant="outline">Cancel</Button>
                        </Link>
                        <Button type="submit" disabled={processing || variants.length === 0}>
                            {processing && <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />}
                            Create Product
                        </Button>
                    </div>
                </form>
            </div>
        </>
    );
}

ProductsCreate.layout = {
    breadcrumbs: [
        { title: 'Dashboard', href: dashboard() },
        { title: 'Products', href: products() },
        { title: 'Create', href: productsCreate().url },
    ],
};
