// resources/js/components/ui/searchable-select.tsx
import { CheckIcon, ChevronDownIcon, Search } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';

import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';

export type SearchableSelectOption = {
    value: string;
    label: string;
};

export type SearchableSelectProps = {
    value: string;
    onValueChange: (value: string) => void;
    options: SearchableSelectOption[];
    placeholder?: string;
    searchPlaceholder?: string;
    emptyText?: string;
    className?: string;
    disabled?: boolean;
};

export function SearchableSelect({
    value,
    onValueChange,
    options,
    placeholder,
    searchPlaceholder = 'Search...',
    emptyText = 'No results',
    className,
    disabled = false,
}: SearchableSelectProps) {
    const [open, setOpen] = useState(false);
    const [query, setQuery] = useState('');
    const [position, setPosition] = useState<{
        top: number;
        left: number;
        width: number;
    } | null>(null);
    const triggerRef = useRef<HTMLButtonElement>(null);
    const dropdownRef = useRef<HTMLDivElement>(null);

    const selected = options.find((o) => o.value === value);

    const filtered = useMemo(() => {
        const q = query.trim().toLowerCase();

        if (!q) {
            return options;
        }

        return options.filter((o) => o.label.toLowerCase().includes(q));
    }, [options, query]);

    const openDropdown = () => {
        const el = triggerRef.current;

        if (!el) {
            return;
        }

        const rect = el.getBoundingClientRect();

        setPosition({ top: rect.bottom + 4, left: rect.left, width: rect.width });
        setQuery('');
        setOpen(true);
    };

    useEffect(() => {
        if (!open) {
            setPosition(null);

            return;
        }

        const onMouseDown = (e: MouseEvent) => {
            if (
                dropdownRef.current &&
                !dropdownRef.current.contains(e.target as Node)
            ) {
                setOpen(false);
            }
        };

        const onKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Escape') {
                setOpen(false);
            }
        };

        const onScroll = (e: Event) => {
            if (
                dropdownRef.current &&
                dropdownRef.current.contains(e.target as Node)
            ) {
                return;
            }

            setOpen(false);
        };

        document.addEventListener('mousedown', onMouseDown);
        document.addEventListener('keydown', onKeyDown);
        window.addEventListener('scroll', onScroll, true);

        return () => {
            document.removeEventListener('mousedown', onMouseDown);
            document.removeEventListener('keydown', onKeyDown);
            window.removeEventListener('scroll', onScroll, true);
        };
    }, [open]);

    return (
        <>
            <button
                ref={triggerRef}
                type="button"
                disabled={disabled}
                aria-haspopup="listbox"
                aria-expanded={open}
                onClick={openDropdown}
                className={cn(
                    'border-input focus-visible:border-ring focus-visible:ring-ring/50 dark:bg-input/30 dark:hover:bg-input/50 flex h-9 w-fit items-center justify-between gap-2 rounded-md border bg-transparent px-3 py-2 text-sm whitespace-nowrap shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*="size-"])]:size-4',
                    className,
                )}
            >
                <span
                    className={cn(
                        'line-clamp-1 text-left',
                        !selected && 'text-muted-foreground',
                    )}
                >
                    {selected ? selected.label : placeholder}
                </span>
                <ChevronDownIcon className="size-4 shrink-0 opacity-50" />
            </button>
            {open && position && (
                <div
                    ref={dropdownRef}
                    style={{
                        position: 'fixed',
                        top: position.top,
                        left: position.left,
                        width: position.width,
                        zIndex: 50,
                    }}
                    className="bg-popover text-popover-foreground flex min-w-40 flex-col overflow-hidden rounded-md border shadow-md"
                >
                    <div className="flex items-center gap-2 border-b px-2 py-1.5">
                        <Search className="size-4 shrink-0 opacity-50" />
                        <Input
                            autoFocus
                            value={query}
                            onChange={(e) => setQuery(e.target.value)}
                            placeholder={searchPlaceholder}
                            className="h-8 border-0 shadow-none focus-visible:ring-0"
                        />
                    </div>
                    <div className="max-h-56 overflow-y-auto p-1">
                        {filtered.length === 0 && (
                            <p className="px-2 py-6 text-center text-sm text-muted-foreground">
                                {emptyText}
                            </p>
                        )}
                        {filtered.map((o) => (
                            <button
                                key={o.value}
                                type="button"
                                onClick={() => {
                                    onValueChange(o.value);
                                    setOpen(false);
                                }}
                                className={cn(
                                    'flex w-full items-center justify-between gap-2 rounded-sm px-2 py-1.5 pr-8 text-left text-sm outline-none hover:bg-accent hover:text-accent-foreground',
                                    o.value === value &&
                                        'bg-accent text-accent-foreground',
                                )}
                            >
                                <span className="line-clamp-1">{o.label}</span>
                                {o.value === value && (
                                    <CheckIcon className="size-4 shrink-0" />
                                )}
                            </button>
                        ))}
                    </div>
                </div>
            )}
        </>
    );
}

// resources/js/components/forms/SearchableSelect.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

type Option = { value: string | number; label: string };

const props = withDefaults(defineProps<{
    options: Option[];
    placeholder?: string;
    searchPlaceholder?: string;
}>(), {
    placeholder: '',
    searchPlaceholder: '',
});
const { t } = useI18n();

const modelValue = defineModel<string | number>({ default: '' });
const isOpen = ref(false);
const query = ref('');
const selectedLabel = computed(() => props.options.find((option) => String(option.value) === String(modelValue.value))?.label ?? '');
const filteredOptions = computed(() => props.options.filter((option) => option.label.toLowerCase().includes(query.value.toLowerCase())));

function selectOption(option: Option): void {
    modelValue.value = option.value;
    query.value = '';
    isOpen.value = false;
}
</script>

<template>
    <div class="relative">
        <button type="button" class="flex min-h-11 w-full items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-3 text-left text-sm text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100" @click="isOpen = !isOpen">
            <span :class="selectedLabel ? '' : 'text-slate-400'">{{ selectedLabel || placeholder || t('common.select_option') }}</span>
            <span aria-hidden="true">&#9662;</span>
        </button>
        <div v-if="isOpen" class="absolute z-30 mt-1 w-full rounded-xl border border-slate-200 bg-white p-2 shadow-xl dark:border-slate-700 dark:bg-slate-900">
            <input v-model="query" type="search" :placeholder="searchPlaceholder || t('common.search_options')" :aria-label="searchPlaceholder || t('common.search_options')" class="mb-2 min-h-9 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-blue-400 dark:border-slate-700 dark:bg-slate-800" autofocus @keydown.escape="isOpen = false" />
            <div class="max-h-56 overflow-y-auto">
                <button v-for="option in filteredOptions" :key="option.value" type="button" class="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-blue-50 dark:hover:bg-slate-800" @mousedown.prevent @click="selectOption(option)">{{ option.label }}</button>
                <p v-if="!filteredOptions.length" class="px-3 py-2 text-sm text-slate-400">{{ t('common.no_options') }}</p>
            </div>
        </div>
    </div>
</template>
